fix?
Run yarn run test
yarn run v1.22.18
$ jest
● Validation Error:
  Test environment jest-environment-jsdom cannot be found. Make sure the testEnvironment configuration option points to an existing node module.
  Configuration Documentation:
  https://jestjs.io/docs/configurati
As of Jest 28 "jest-environment-jsdom" is no longer shipped by default, make sure to install it separately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.